// Role model source: DB `roles` table (users.role) — hierarchy: super_admin > admin > department_head > employee
// The DB's `manage_sops` permission is coarse (granted to super_admin/admin/department_head, not employee).
// This file adds per-action + per-scope granularity on top of it for CREATE/EDIT/DELETE/PUBLISH/ARCHIVE/ASSIGN/SHARE.
// VIEW_AUDIT_LOG is NOT part of manage_sops — it maps to the separate `view_audit_logs` permission,
// which per role_permissions seed data belongs to super_admin ONLY.

export const SOP_ROLE = Object.freeze({
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  DEPARTMENT_HEAD: 'department_head',
  EMPLOYEE: 'employee',
});

export const SOP_ACTION = Object.freeze({
  VIEW: 'view',
  CREATE: 'create',
  EDIT: 'edit',
  DELETE: 'delete',
  SUBMIT_FOR_REVIEW: 'submit_for_review',
  APPROVE: 'approve',
  REJECT: 'reject',
  PUBLISH: 'publish',
  ARCHIVE: 'archive',
  RESTORE_VERSION: 'restore_version',
  ASSIGN: 'assign',
  ACKNOWLEDGE: 'acknowledge',
  SHARE: 'share',
  VIEW_AUDIT_LOG: 'view_audit_log',
});

export const PERMISSION_SCOPE = Object.freeze({
  ALL: 'all',
  OWN_DEPARTMENT: 'own_department',
  ASSIGNED_ONLY: 'assigned_only',
  SELF: 'self',
  NONE: 'none',
});

export const SOP_PERMISSION_MATRIX = Object.freeze({
  [SOP_ROLE.SUPER_ADMIN]: {
    [SOP_ACTION.VIEW]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.CREATE]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.EDIT]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.DELETE]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.SUBMIT_FOR_REVIEW]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.APPROVE]: PERMISSION_SCOPE.ASSIGNED_ONLY,
    [SOP_ACTION.REJECT]: PERMISSION_SCOPE.ASSIGNED_ONLY,
    [SOP_ACTION.PUBLISH]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.ARCHIVE]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.RESTORE_VERSION]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.ASSIGN]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.ACKNOWLEDGE]: PERMISSION_SCOPE.SELF,
    [SOP_ACTION.SHARE]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.VIEW_AUDIT_LOG]: PERMISSION_SCOPE.ALL, // view_audit_logs permission ✓
  },
  [SOP_ROLE.ADMIN]: {
    [SOP_ACTION.VIEW]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.CREATE]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.EDIT]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.DELETE]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.SUBMIT_FOR_REVIEW]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.APPROVE]: PERMISSION_SCOPE.ASSIGNED_ONLY,
    [SOP_ACTION.REJECT]: PERMISSION_SCOPE.ASSIGNED_ONLY,
    [SOP_ACTION.PUBLISH]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.ARCHIVE]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.RESTORE_VERSION]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.ASSIGN]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.ACKNOWLEDGE]: PERMISSION_SCOPE.SELF,
    [SOP_ACTION.SHARE]: PERMISSION_SCOPE.ALL,
    [SOP_ACTION.VIEW_AUDIT_LOG]: PERMISSION_SCOPE.NONE, // admin does NOT hold view_audit_logs per seed
  },
  [SOP_ROLE.DEPARTMENT_HEAD]: {
    [SOP_ACTION.VIEW]: PERMISSION_SCOPE.OWN_DEPARTMENT,
    [SOP_ACTION.CREATE]: PERMISSION_SCOPE.OWN_DEPARTMENT,
    [SOP_ACTION.EDIT]: PERMISSION_SCOPE.OWN_DEPARTMENT,
    [SOP_ACTION.DELETE]: PERMISSION_SCOPE.OWN_DEPARTMENT,
    [SOP_ACTION.SUBMIT_FOR_REVIEW]: PERMISSION_SCOPE.OWN_DEPARTMENT,
    [SOP_ACTION.APPROVE]: PERMISSION_SCOPE.ASSIGNED_ONLY,
    [SOP_ACTION.REJECT]: PERMISSION_SCOPE.ASSIGNED_ONLY,
    [SOP_ACTION.PUBLISH]: PERMISSION_SCOPE.OWN_DEPARTMENT,
    [SOP_ACTION.ARCHIVE]: PERMISSION_SCOPE.OWN_DEPARTMENT,
    [SOP_ACTION.RESTORE_VERSION]: PERMISSION_SCOPE.OWN_DEPARTMENT,
    [SOP_ACTION.ASSIGN]: PERMISSION_SCOPE.OWN_DEPARTMENT,
    [SOP_ACTION.ACKNOWLEDGE]: PERMISSION_SCOPE.SELF,
    [SOP_ACTION.SHARE]: PERMISSION_SCOPE.OWN_DEPARTMENT,
    [SOP_ACTION.VIEW_AUDIT_LOG]: PERMISSION_SCOPE.NONE, // dept_head does NOT hold view_audit_logs per seed
  },
  [SOP_ROLE.EMPLOYEE]: {
    [SOP_ACTION.VIEW]: PERMISSION_SCOPE.ASSIGNED_ONLY,
    [SOP_ACTION.CREATE]: PERMISSION_SCOPE.NONE,
    [SOP_ACTION.EDIT]: PERMISSION_SCOPE.NONE,
    [SOP_ACTION.DELETE]: PERMISSION_SCOPE.NONE,
    [SOP_ACTION.SUBMIT_FOR_REVIEW]: PERMISSION_SCOPE.NONE,
    [SOP_ACTION.APPROVE]: PERMISSION_SCOPE.ASSIGNED_ONLY, // e.g. named as a Position-type approver despite role
    [SOP_ACTION.REJECT]: PERMISSION_SCOPE.ASSIGNED_ONLY,
    [SOP_ACTION.PUBLISH]: PERMISSION_SCOPE.NONE,
    [SOP_ACTION.ARCHIVE]: PERMISSION_SCOPE.NONE,
    [SOP_ACTION.RESTORE_VERSION]: PERMISSION_SCOPE.NONE,
    [SOP_ACTION.ASSIGN]: PERMISSION_SCOPE.NONE,
    [SOP_ACTION.ACKNOWLEDGE]: PERMISSION_SCOPE.SELF,
    [SOP_ACTION.SHARE]: PERMISSION_SCOPE.NONE,
    [SOP_ACTION.VIEW_AUDIT_LOG]: PERMISSION_SCOPE.NONE,
  },
});

// Static (role-only) lookup. Resolves to a SCOPE, not a boolean — callers still need to check
// that scope against the actual record (department_id match, workflow_steps approver match, etc).
// That row-level resolution lives in services/permission.helper.js (Phase 1) and
// services/workflow.service.js (Phase 6) for the APPROVE/REJECT case specifically.
export function getStaticScope(role, action) {
  return SOP_PERMISSION_MATRIX[role]?.[action] ?? PERMISSION_SCOPE.NONE;
}